export let terms=[
    {
        title:"",
        discription:"Welcome to Myntra.This document is an electronic record in terms of Information Technology Act, 2000 and published in accordance with the provisions of Rule 3 ) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of Myntra marketplace platform - www.myntra.com (hereinafter referred to as 'Platform')The Platform is owned by Myntra Designs Private Limited, having its registered office at Buildings Alyssa, Begonia and Clover situated in Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Varthur Hobli, Bengaluru – 560103, India and its branch office at Plot 82 A - 2nd and 3rd Floor, Sector 18 Gurugram Haryana, India.Your use of the Myntra and services and tools are governed by the following terms and conditions ('Terms of Use') as applicable to the Myntra including the applicable policies which are incorporated herein by way of reference. By mere use of the Myntra, You shall be contracting with Myntra Designs Private Limited, the owner of the Platform. These terms and conditions including the policies constitute Your binding obligations, with Myntra.For the purpose of these Terms of Use, wherever the context so requires 'You' or 'User' shall mean any natural or legal person who has agreed to become a buyer on Platform by providing data while registering on the Platform as Registered User. The term 'Myntra','We','Us','Our' shall mean Myntra Designs Private Limited and its affiliates.When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. You shall ensure to review these Terms of Use periodically for updates/changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Myntra Policies including but not limited to Privacy Policy as amended from time to time "
    },
    {
        title:"1. User Account, Password, and Security:",
        discription:"If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or not in accordance with this Terms of Use, We shall have the right to indefinitely suspend or terminate or block Your access on the Platform.If there is reason to believe that there is likely to be a breach of security or misuse of Your account, We may request You to change the password or we may suspend Your account without any liability to Myntra, for such period of time as we deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.In the event of a device being associated with multiple logins or sign ups, as a measure to enhance customer's security and privacy as well as safeguarding your sensitive information for any potential risks, Myntra sometimes consider moderating users and their association with devices while using the Myntra app or website.Your mobile phone number is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through an OTP verification. You agree that Myntra shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Platform. You agree to immediately notify Myntra of any unauthorized use/breach of your password or account.If You share or allow others to have access to Your account on the Platform ('Account'), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information, You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences therefrom.If You have not accessed Platform for a period of 2 (two) Years, Your data (including transactional data) will be deleted from Our record and You will not be able to access such data."
    },
    {
        title:"2. Services Offered:",
        discription:'Myntra provides a number of Internet-based services through the Platform. One such Service enables Users to purchase original merchandise such as clothing, footwear and accessories from various fashion and lifestyle brands (collectively, "Products"). The Products can be purchased through the Platform through various methods of payments offered. The sale/purchase of Products shall be additionally governed by specific policies of sale, like cancellation policy, exchange policy, return policy, etc. (which are found on the FAQ tab on the Platform and all of which are incorporated here by reference). It is clarified that at the time of creating a return request, users are required to confirm (via a check box click) that the product being returned is unused and has the original tags intact. If the product returned by the user is used, damaged or if the original tags are missing, the user’s return request shall be declined, and the said product shall be re-shipped back to the customer. In the event that the return request is declined, the user shall not be eligible for a refund, and Myntra assumes no liability in this regard. Further, in the event that the user fails to accept the receipt of the said re-shipped product, the user shall continue to be not eligible for a refund, and Myntra assumes no liability with respect to the return or refund for the said re-shipped product. In addition, these Terms of Use may be further supplemented by Product specific conditions, which may be displayed with that Product.Myntra does not warrant that Product description or other content on the Platform is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.'
    },
    {
        title:"3. Platform for Transaction and Communication:"
        ,discription:"The Users utilize to meet and interact with one another for their transactions on the Platform. Myntra is not and cannot be a party to or control in any manner any transaction between the Myntra's Users. Henceforward:All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. Myntra does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers.Myntra does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Platform.Myntra is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. Myntra cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Platform.At no time shall Myntra hold any right, title or interest over the products nor shall Myntra have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers.The Myntra is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Myntra is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer. At no time shall Myntra hold any any right, title or interest over the products nor shall Myntra have any obligations or liabilities in respect of such contract. Myntra is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.Pricing on any product(s) as is reflected on the Platform may due to some technical issue, typographical error or product information published by seller may be incorrectly reflected and in such an event seller may cancel such your order(s).You release and indemnify Myntra and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Myntra and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, Myntra cannot take responsibility or control the information provided by other Users which is made available on the Platform."
    },
    {
        title:"4. Disclaimer of Warranties and Liability:",
        discription:'All the materials and products (including but not limited to software) and services, included on or otherwise made available to You through Platform are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, Myntra does not warrant that: Platform will be constantly available, or available at all or The information on Platform is complete, true, accurate or non-misleading. All the Products sold on Platform are governed by different state laws and if Seller is unable to deliver such Products due to implications of different state laws, Seller will return or will give credit for the amount (if any) received in advance by Seller from the sale of such Product that could not be delivered to You. You will be required to enter a valid phone number while placing an order on the Platform. By registering Your phone number with us, You consent to be contacted by Us via phone calls and/or SMS notifications, in case of any order or shipment or delivery related updates. We will not use your personal information to initiate any promotional phone calls or SMS.'
    },
    {
        title:"5. Selling:",
        discription:"As a registered seller, you are allowed to list item(s) for sale on the Platform in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on the Platform. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Platform. All listed items must be kept in stock for successful fulfilment of sales. The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Platform. Myntra reserves the right to delete such multiple listings of the same product listed by you in various categories. We may provide you alternation services (limited to alteration of length, alteration of the waist size) for the garments purchased by You from Us. This service shall be free of cost and no amount would be collected from You for such alteration. However, a nominal fee as mentioned by Myntra at the time of creating the alteration request (inclusive of service tax) would be applicable as convenience charge towards pick up and drop of the garments or towards tailor visit (wherever applicable)"
    }
]